# Generated by Django 5.0.6 on 2025-06-13 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libele', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=15)),
                ('datecreate', models.DateTimeField(auto_now_add=True)),
                ('dateupdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conducteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarccar', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('datecreate', models.DateTimeField(auto_now_add=True)),
                ('dateupdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Gare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('telephone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heuredepart', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeprofil', models.CharField(max_length=100)),
                ('libele', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree', models.FloatField()),
                ('distance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SegmentHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heuredepart', models.TimeField()),
                ('heurearrivee', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ligne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree', models.FloatField()),
                ('arrive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ligne_arrive', to='TravelTicket.gare')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ligne_depart', to='TravelTicket.gare')),
                ('arretligne', models.ManyToManyField(to='TravelTicket.ville')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_reservation', models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True)),
                ('places_reservees', models.PositiveIntegerField(default=1)),
                ('montant_reservation', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('datereservation', models.DateTimeField(auto_now_add=True)),
                ('dateupdate', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TravelTicket.client')),
            ],
        ),
        migrations.CreateModel(
            name='Payement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('modepayement', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=100)),
                ('numeropayement', models.CharField(max_length=100)),
                ('datepayement', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='TravelTicket.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='SegmentSegmentHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placedisponible', models.IntegerField(default=0)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravelTicket.segment')),
                ('segmenthoraire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravelTicket.segmenthoraire')),
            ],
            options={
                'unique_together': {('segment', 'segmenthoraire')},
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='voyage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='TravelTicket.segmentsegmenthoraire'),
        ),
        migrations.CreateModel(
            name='TypeCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libele', models.CharField(max_length=100)),
                ('avantages', models.ManyToManyField(to='TravelTicket.avantage')),
            ],
        ),
        migrations.AddField(
            model_name='segment',
            name='typevoyage',
            field=models.ManyToManyField(to='TravelTicket.typecar'),
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datecreate', models.DateTimeField(auto_now_add=True)),
                ('dateupdate', models.DateTimeField(auto_now=True)),
                ('Horaire', models.ManyToManyField(to='TravelTicket.horaire')),
                ('date', models.ManyToManyField(to='TravelTicket.date')),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravelTicket.ligne')),
                ('typevoyage', models.ManyToManyField(to='TravelTicket.typecar')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=100)),
                ('couleur', models.CharField(max_length=100)),
                ('capacite', models.IntegerField()),
                ('datecreate', models.DateTimeField(auto_now_add=True)),
                ('dateupdate', models.DateTimeField(auto_now=True)),
                ('Conducteur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TravelTicket.conducteur')),
                ('typecar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TravelTicket.typecar')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('datecreate', models.DateTimeField(auto_now_add=True)),
                ('dateupdate', models.DateTimeField(auto_now=True)),
                ('gare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravelTicket.gare')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TravelTicket.profil')),
            ],
        ),
        migrations.AddField(
            model_name='segment',
            name='villearrivee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villearrivee', to='TravelTicket.ville'),
        ),
        migrations.AddField(
            model_name='segment',
            name='villedepart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villedepart', to='TravelTicket.ville'),
        ),
        migrations.AddField(
            model_name='gare',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravelTicket.ville'),
        ),
        migrations.CreateModel(
            name='SegmentTypeCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarif', models.FloatField()),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravelTicket.segment')),
                ('typecar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravelTicket.typecar')),
            ],
            options={
                'unique_together': {('segment', 'typecar')},
            },
        ),
    ]
