# Generated by Django 5.0.6 on 2025-07-07 08:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libele', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('couleur', models.CharField(choices=[('Blanc', 'Blanc'), ('Noir', 'Noir'), ('Rouge', 'Rouge'), ('Vert', 'Vert'), ('Bleu', 'Bleu'), ('Gris', 'Gris'), ('Jaune', 'Jaune'), ('Orange', 'Orange'), ('Marron', 'Marron'), ('Violet', 'Violet')], max_length=100)),
                ('capacite', models.IntegerField()),
                ('datecreate', models.DateTimeField(auto_now_add=True)),
                ('dateupdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=15)),
                ('mugepci', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('datecreate', models.DateTimeField(auto_now_add=True)),
                ('dateupdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Gare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=14, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('datecreate', models.DateTimeField(auto_now_add=True)),
                ('dateupdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heuredepart', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Passager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=100)),
                ('mugepci', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('destination', models.CharField(blank=True, max_length=100, null=True)),
                ('datecreate', models.DateTimeField(auto_now_add=True)),
                ('dateupdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeprofil', models.CharField(max_length=100)),
                ('libele', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree', models.TimeField()),
                ('distance', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('datecreate', models.DateTimeField(auto_now_add=True)),
                ('dateupdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conducteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=14, unique=True)),
                ('datecreate', models.DateTimeField(auto_now_add=True)),
                ('dateupdate', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TravelTicket.car')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('gare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='TravelTicket.gare')),
            ],
        ),
        migrations.CreateModel(
            name='Ligne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datecreate', models.DateTimeField(auto_now_add=True)),
                ('dateupdate', models.DateTimeField(auto_now=True)),
                ('arrive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrive', to='TravelTicket.gare')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depart', to='TravelTicket.gare')),
                ('villeligne', models.ManyToManyField(related_name='villeligne', to='TravelTicket.gare')),
            ],
        ),
        migrations.CreateModel(
            name='Payement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('modepayement', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=100)),
                ('numeropayement', models.CharField(max_length=100)),
                ('datepayement', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='TravelTicket.client')),
            ],
        ),
        migrations.CreateModel(
            name='SegmentTypeCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarif', models.IntegerField()),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment', to='TravelTicket.segment')),
            ],
        ),
        migrations.CreateModel(
            name='SegmentVoyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plase_disponible', models.IntegerField(default=0)),
                ('heuredepart', models.TimeField()),
                ('heurearrivee', models.TimeField(blank=True, null=True)),
                ('tarif', models.IntegerField(default=0)),
                ('datecreate', models.DateTimeField(auto_now_add=True)),
                ('dateupdate', models.DateTimeField(auto_now=True)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravelTicket.segmenttypecar')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_reservation', models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True)),
                ('places_reservees', models.PositiveIntegerField(default=1)),
                ('montant_reservation', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('Annulé', 'Annulé'), ('Validé', 'Validé'), ('En attente', 'En attente')], default='En attente', max_length=20)),
                ('datereservation', models.DateTimeField(auto_now_add=True)),
                ('dateupdate', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TravelTicket.client')),
                ('numeropayement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='TravelTicket.payement')),
                ('passager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passager', to='TravelTicket.passager')),
                ('segmentvoyage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TravelTicket.segmentvoyage')),
            ],
        ),
        migrations.CreateModel(
            name='TypeCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libele', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('datecreate', models.DateTimeField(auto_now_add=True)),
                ('dateupdate', models.DateTimeField(auto_now=True)),
                ('avantages', models.ManyToManyField(to='TravelTicket.avantage')),
            ],
        ),
        migrations.AddField(
            model_name='segmenttypecar',
            name='typecar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typecar', to='TravelTicket.typecar'),
        ),
        migrations.AddField(
            model_name='segment',
            name='typevoyage',
            field=models.ManyToManyField(to='TravelTicket.typecar'),
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datecreate', models.DateTimeField(auto_now_add=True)),
                ('dateupdate', models.DateTimeField(auto_now=True)),
                ('date', models.ManyToManyField(to='TravelTicket.date')),
                ('horaire', models.ManyToManyField(to='TravelTicket.horaire')),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravelTicket.ligne')),
                ('typevoyage', models.ManyToManyField(to='TravelTicket.typecar')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='typecar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TravelTicket.typecar'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('datecreate', models.DateTimeField(auto_now_add=True)),
                ('dateupdate', models.DateTimeField(auto_now=True)),
                ('gare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravelTicket.gare')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TravelTicket.profil')),
            ],
        ),
        migrations.AddField(
            model_name='segment',
            name='villearrivee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villearrivee', to='TravelTicket.ville'),
        ),
        migrations.AddField(
            model_name='segment',
            name='villedepart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villedepart', to='TravelTicket.ville'),
        ),
        migrations.AddField(
            model_name='gare',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ville', to='TravelTicket.ville'),
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerovoyage', models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True)),
                ('datecreates', models.DateTimeField(auto_now_add=True)),
                ('dateupdates', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('Prévu', 'Prévu'), ('Effectué', 'Effectué'), ('Annulé', 'Annulé'), ('En cours', 'En cours')], default='Prévu', max_length=50)),
                ('arrets', models.ManyToManyField(blank=True, to='TravelTicket.gare')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TravelTicket.car')),
                ('conducteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TravelTicket.conducteur')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravelTicket.date')),
                ('horaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravelTicket.horaire')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravelTicket.programme')),
                ('typecar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravelTicket.typecar')),
            ],
        ),
        migrations.AddField(
            model_name='segmentvoyage',
            name='voyage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravelTicket.voyage'),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('adresse', models.CharField(max_length=255)),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravelTicket.voyage')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='segmenttypecar',
            unique_together={('segment', 'typecar')},
        ),
    ]
