# Generated by Django 5.0.6 on 2025-07-01 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelTicket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligne',
            name='villeligne',
            field=models.ManyToManyField(related_name='villeligne', to='TravelTicket.gare'),
        ),
    ]
