# Generated by Django 5.0.6 on 2025-06-13 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelTicket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ville',
            name='region',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('gare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravelTicket.gare')),
            ],
        ),
    ]
