# Generated by Django 5.0.6 on 2025-06-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelTicket', '0002_ville_region_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='typecar',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
