# Generated by Django 5.0.6 on 2025-07-01 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelTicket', '0002_alter_ligne_villeligne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentvoyage',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravelTicket.segmenttypecar'),
        ),
    ]
