# Generated by Django 5.0.6 on 2025-07-01 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelTicket', '0003_alter_segmentvoyage_segment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmenttypecar',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment', to='TravelTicket.segment'),
        ),
        migrations.AlterField(
            model_name='segmenttypecar',
            name='typecar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typecar', to='TravelTicket.typecar'),
        ),
    ]
