# Generated by Django 5.0.6 on 2025-06-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelTicket', '0003_typecar_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conducteur',
            name='tarccar',
        ),
        migrations.AddField(
            model_name='conducteur',
            name='contact',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
