# Generated by Django 5.0.6 on 2025-06-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelTicket', '0004_remove_conducteur_tarccar_conducteur_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conducteur',
            name='contact',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
