# Generated by Django 5.0.6 on 2025-06-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelTicket', '0005_alter_conducteur_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conducteur',
            name='contact',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
