# Generated by Django 5.0.6 on 2025-06-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelTicket', '0006_alter_conducteur_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='couleur',
            field=models.CharField(choices=[('Blanc', 'Blanc'), ('Noir', 'Noir'), ('Rouge', 'Rouge'), ('Vert', 'Vert'), ('Bleu', 'Bleu'), ('Gris', 'Gris'), ('Jaune', 'Jaune'), ('Orange', 'Orange'), ('Marron', 'Marron'), ('Violet', 'Violet')], max_length=100),
        ),
    ]
