# Generated by Django 5.0.6 on 2025-06-16 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TravelTicket', '0007_car_model_alter_car_couleur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='Conducteur',
            new_name='conducteur',
        ),
    ]
