# Generated by Django 5.0.6 on 2025-06-16 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TravelTicket', '0008_rename_conducteur_car_conducteur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gare',
            old_name='telephone',
            new_name='contact',
        ),
    ]
