# Generated by Django 5.0.6 on 2025-06-17 09:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelTicket', '0009_rename_telephone_gare_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='gare',
            name='datecreate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gare',
            name='dateupdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='typecar',
            name='datecreate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typecar',
            name='dateupdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ville',
            name='datecreate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ville',
            name='dateupdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='gare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='TravelTicket.gare'),
        ),
    ]
