# Generated by Django 5.0.6 on 2025-06-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelTicket', '0010_gare_datecreate_gare_dateupdate_typecar_datecreate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gare',
            name='contact',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='gare',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
