# Generated by Django 5.0.6 on 2025-06-18 08:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelTicket', '0011_alter_gare_contact_alter_gare_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='conducteur',
        ),
        migrations.RemoveField(
            model_name='ligne',
            name='arretligne',
        ),
        migrations.AddField(
            model_name='conducteur',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TravelTicket.car'),
        ),
        migrations.AddField(
            model_name='ligne',
            name='datecreate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ligne',
            name='dateupdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ligne',
            name='villeligne',
            field=models.ManyToManyField(related_name='villeligne', to='TravelTicket.ville'),
        ),
        migrations.AlterField(
            model_name='ligne',
            name='arrive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrive', to='TravelTicket.gare'),
        ),
        migrations.AlterField(
            model_name='ligne',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depart', to='TravelTicket.gare'),
        ),
    ]
