# Generated by Django 5.0.6 on 2025-06-18 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TravelTicket', '0012_remove_car_conducteur_remove_ligne_arretligne_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligne',
            name='duree',
        ),
    ]
