# Generated by Django 5.0.6 on 2025-06-20 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelTicket', '0013_remove_ligne_duree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conducteur',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TravelTicket.car'),
        ),
        migrations.AlterField(
            model_name='gare',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ville', to='TravelTicket.ville'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='distance',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
