# Generated by Django 5.0.6 on 2025-06-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelTicket', '0014_alter_conducteur_car_alter_gare_ville_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='duree',
            field=models.TimeField(),
        ),
    ]
