# Generated by Django 5.0.6 on 2025-06-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelTicket', '0015_alter_segment_duree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmenttypecar',
            name='tarif',
            field=models.IntegerField(),
        ),
    ]
